app = 'embedding'
primary_region = 'sjc'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
      type = "requests"
      soft_limit = 10
      hard_limit = 100

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 8
